
---
- name: "Testing services added"
  hosts: localhost
  
  tasks:
  - name: mapping profilename
    command: echo "FSW_PRIMARY:FSW_SECONDARY"
    register: profilename
    
  - name: mapping profilename
    command: echo "FSW_SECONDARY"
    register: profilename2
    
  - name: setting fact
    set_fact: 
      prof: "{{ profilename.stdout|trim }}"
    when: profilename.stdout is search(":")
      
  - name: setting fact2
    set_fact:
      prof1: "{{ prof.split(':') }}"
    when: profilename.stdout is search(":")      
  
  - name: creating file
    file:
      path: "{{ item  }}"
      state: touch
    with_items:
      - /tmp/maintenance-deployment-running.{{ prof }}
      - /tmp/maintenance-svc.{{ prof1.0 }}
      - /tmp/maintenance-svc.{{ prof1.1 }}
    when: profilename.stdout is search(":")
    
  - name: creating file2
    file:
      path: "{{ item }}"
      state: touch
    with_items:
      - /tmp/maintenance-deployment-running.{{ prof }}
      - /tmp/maintenance-svc.{{ prof }}
    when: profilename2.stdout is not search(":")
